apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aggregator-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
      - name: aggregator-service
        image: us.gcr.io/sock-shop-207010/aggregator:latest
        ports:
        - containerPort: 8080
