apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: isodate-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: isodate-service
    spec:
      containers:
      - name: isodate-service
        image: us.gcr.io/sock-shop-207010/iso-date-service:1.0
        ports:
        - containerPort: 3000
