apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: utcdate-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: utcdate-service
    spec:
      containers:
      - name: utcdate-service
        image: us.gcr.io/sock-shop-207010/utc-date-service:latest
        ports:
        - containerPort: 3001
